#!/bin/bash
# Example Linux routing script for split tunneling.
# Generated by NetRoute Pro: https://alexander2k.github.io/netroute-site/
#
# Run as root or with sudo. Routes added here last until reboot —
# for persistence see the Linux guide (systemd-networkd / NetworkManager).

set -euo pipefail

DEV="wg0"          # VPN interface name (wg0, tun0, ppp0, ...)
GW="10.0.0.1"      # VPN gateway IP (or use only "dev $DEV" if VPN is point-to-point)

ip route add 1.1.1.0/24    via "$GW" dev "$DEV"
ip route add 8.8.8.0/24    via "$GW" dev "$DEV"
ip route add 162.159.0.0/16 via "$GW" dev "$DEV"

# Verify with: ip route show
# Remove with: ip route del <CIDR>
